Update IIAuctionHouse.yaml

diff --git a/.github/workflows/IIAuctionHouse.yaml b/.github/workflows/IIAuctionHouse.yaml
--- a/.github/workflows/IIAuctionHouse.yaml
+++ b/.github/workflows/IIAuctionHouse.yaml
@@ -37,8 +37,11 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - run: npm ci
-    - run: npm test
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: '*.xml'    # Path to test results
+          reporter: jest-junit 
     
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v1.8.1
@@ -51,15 +54,7 @@ jobs:
     - name: Build
       run: dotnet build --configuration Release --no-restore
 
-
     - name: Test
       run: dotnet test
-      
-    - name: Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: '*.xml'    # Path to test results
-          reporter: jest-junit 
+  
 
